# Generated by Django 3.1.5 on 2021-04-29 20:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210430_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=10),
        ),
    ]
