# Generated by Django 3.1.5 on 2021-05-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210430_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='long',
        ),
    ]
