# Generated by Django 3.1.5 on 2021-05-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210504_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='timestamp',
        ),
    ]
